refactor(kernel-flat): move all reduction kernel functions to file `flat_reduce.hpp`
This commit is applied to fix a compiling error `flat_imp_one_pass.hpp:58:6: error:
use of undeclared identifier 'flat_reduce_in_vector'`, which does not effect the meaning
of the code.